---
- name: Frontend Build Configuration
  hosts: localhost
  become: true

  tasks:

    - name: Update environment
      path: ../src/environment/environment.ts
      lineinfile:
        regexp: 'apiUrl'
